### ISSUE TITLE
package import issue

### ISSUE THREAD

**Issue by romain-lopez** [openopt/chop#5]
installed constopt-pytorch via git clone and pip install -e .

the following lines fail:
import constopt
constopt.stochastic.PGD

>module 'constopt' has no attribute 'stochastic'

these ones work
import constopt
import constopt.stochastic
constopt.stochastic.PGD

**Comment by GeoffNN** [comment]
It works on my machine. Can you check you have the latest version?

**Comment by GeoffNN** [comment]
Ping on this issue. We have updated the setup: you should now install the repo by cloning and running `python setup.py develop` in your conda environment.

**Comment by GeoffNN** [comment]
A lot has changed since; Closing. Let me know if you still have problems.
