### ISSUE TITLE
Website with docs and examples

### ISSUE THREAD

**Issue by GeoffNN** [openopt/chop#9]

**Comment by GeoffNN** [comment]
As a sub-issue : make sure LaTeX works for the docstrings when building the docs.

**Comment by GeoffNN** [comment]
@fabianp let me know how I can help!

**Comment by fabianp** [comment]
Implemented in #27

**Comment by GeoffNN** [comment]
I think we should keep this open as a Todo, until the website is online.

**Comment by fabianp** [comment]
Good idea
